version: '2.1'
services:
  app:
    build: .
    image: zenodo:latest
    environment:
      - "INVENIO_ACCOUNTS_SESSION_REDIS_URL=redis://cache:6379/1"
      - "INVENIO_BROKER_URL=amqp://guest:guest@mq:5672//"
      - "INVENIO_CELERY_BROKER_URL=amqp://guest:guest@mq:5672//"
      - "INVENIO_QUEUES_BROKER_URL=amqp://guest:guest@mq:5672//"
      - "INVENIO_CACHE_REDIS_URL=redis://cache:6379/0"
      - "INVENIO_CACHE_TYPE=redis"
      - "INVENIO_CELERY_RESULT_BACKEND=redis://cache:6379/2"
      - "INVENIO_SEARCH_ELASTIC_HOSTS=['es:9200']"
      - "INVENIO_SECRET_KEY=CHANGE_ME"
      - "INVENIO_SESSION_COOKIE_SECURE=True"
      - "INVENIO_SQLALCHEMY_DATABASE_URI=postgresql://zenodo:zenodo@db/zenodo"
      - "INVENIO_WSGI_PROXIES=2"
      - "FLASK_DEBUG=${FLASK_DEBUG:-on}"
  lb:
    build: ./docker/haproxy/
    image: zenodo-lb:latest
    restart: "always"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
  frontend:
    build: ./docker/nginx/
    image: zenodo-frontend:latest
    restart: "always"
    ports:
      - "81:80"
      - "444:443"
  cache:
    image: redis
    restart: "always"
    read_only: true
    ports:
      - "6379:6379"
  db:
    build: ./docker/postgres/
    image: zenodo-postgres
    command: postgres
    restart: "always"
    environment:
      - "POSTGRES_PASSWORD=postgres"
      - "POSTGRES_USER=admin"
    ports:
      - "5432:5432"
  mq:
    image: rabbitmq:3-management
    restart: "always"
    ports:
      - "15672:15672"
      - "5672:5672"
  es:
    build: ./docker/es/
    image: zenodo-es:7.1.1
    restart: "always"
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g
    ports:
      - "9200:9200"
      - "9300:9300"
  kibana:
    build: ./docker/kibana/
    image: zenodo-kibana:4.3
    restart: "always"
    command: kibana
    ports:
      - "5601:5601"
    environment:
      - "ELASTICSEARCH_URL=http://es:9200"
  flower:
    image: mher/flower
    command: --broker=amqp://guest:guest@mq:5672// --broker_api=http://guest:guest@mq:15672/api/
    ports:
      - "5555:5555"
